baseURL = "https://cuongvn98.github.io/"
publishDir = "docs"
languageCode = "vn-vi"
title = "Hirosume blog site"
theme = "cupper-hugo-theme"
disqusShortname = "hirosume"
enableEmoji = true
googleAnalytics = "UA-116855793-1"
[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99.0

[params]
description = "Mình là 1 fullstack developer trẻ , thích golang và là 1 vim user ngoài ra còn thích đọc manga"
homeMetaContent = ""
footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)."
dateFormat = "Jan 2, 2006"
codePenUser = "vungoccuong"
katex = true
hideHeaderLinks = false
search = true
showThemeSwitcher = true
moveFooterToHeader = false
customCss = [

]
customJs = [

]


[menu]

  [[menu.nav]]
  name = "Home"
  url = "/"
  weight = 1.0

  [[menu.nav]]
  name = "Blog"
  url = "/post/"
  weight = 2.0

  [[menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 3.0

  [[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 4.0

  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 5.0

[markup]
defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false

  [markup.highlight]
  codeFences = false
  hl_Lines = ""
  lineNoStart = 1.0
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4.0

  [markup.tableOfContents]
  endLevel = 6.0
  startLevel = 2.0

